import type { Metadata } from "next";
import "./globals.css";
import { ConfigProvider } from "antd";
import faIR from "antd/locale/fa_IR";
import {yekan} from '@/utils/font'
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl" className={`h-full ${yekan.className}!`}>
      <body className={`min-h-full col h-full text-white  ${yekan.className}`}>
        <ConfigProvider locale={faIR} direction="rtl">
          {children}
        </ConfigProvider>
      </body>
    </html>
  );
}
