import type { Metadata } from "next";
import "./globals.css";
import { ConfigProvider, Image } from "antd";
import faIR from "antd/locale/fa_IR";
import { yekan } from "@/utils/font";
import Footer from "@/components/client-side/footer";
import Header from "@/components/client-side/header";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="fa"
      dir="rtl"
      className={`h-full ${yekan.className}!`}
    >
      <body className={`h-full col flex flex-col  text-white  ${yekan.className}`}>
          <Header />
        <ConfigProvider  locale={faIR} direction="rtl">
          <div className=" flex flex-col flex-1">{children}</div>
        </ConfigProvider>
          <Footer />
      </body>
    </html>
  );
}
